/* Comparision Operators */
// Equality (==)
console.log(5 == 5)
console.log(6 == 5)
console.log('hunny' == 'hunny')
console.log('ba' == 'ab')
console.log(6 == '6')
console.log(undefined == null)
// Inequality (!==)
console.log(5 != 5)
console.log('hunny' != 'honey')
console.log(6 != 56)
console.log(5 != '5')
console.log(undefined != null)
// Identity (===)
console.log(6 === '6')
console.log(6 === 6)
console.log(undefined === null)
console.log(undefined === undefined)
// Not Identity (!==)
console.log( 6 !== '6')
console.log( 6 !== 6)
console.log(undefined !== null)
// Greater Than (>)
console.log(5 > 1)
console.log(5 > 100)
// Greater Than or Equal (>=)
console.log(5 >= 5)
console.log(873 >= 5)
// Smaller Than (<)
console.log(1 < 9)
console.log(10 < 9)
// Smaller Than or Equal (<=)
console.log(10 <= 10)
console.log(9 <= 10)

/* Special Comparisions */
console.log(0 == false)
console.log('' == false)
console.log(null == undefined)
console.log(null == false)
console.log(undefined == false)
console.log(NaN == NaN)
console.log(1 == true)
console.log([] == [])
console.log(new Date() == new Date())
console.log({} == {})

/* Logical Operators */
// OR (||)
// AND (&&)
// NOT (!)

/* Special Cases*/

