/* Comparision Operators */
// Equality (==)
console.log(5 == 5)
console.log(6 == 5)
console.log('hunny' == 'hunny')
console.log('ba' == 'ab')
console.log(6 == '6')
console.log(undefined == null)
// Inequality (!==)
console.log(5 != 5)
console.log('hunny' != 'honey')
console.log(6 != 56)
console.log(5 != '5')
console.log(undefined != null)
// Identity (===)
console.log(6 === '6')
console.log(6 === 6)
console.log(undefined === null)
console.log(undefined === undefined)
// Not Identity (!==)
console.log( 6 !== '6')
console.log( 6 !== 6)
console.log(undefined !== null)
// Greater Than (>)
console.log(5 > 1)
console.log(5 > 100)
// Greater Than or Equal (>=)
console.log(5 >= 5)
console.log(873 >= 5)
// Smaller Than (<)
console.log(1 < 9)
console.log(10 < 9)
// Smaller Than or Equal (<=)
console.log(10 <= 10)
console.log(9 <= 10)

/* Special Comparisions */
console.log(0 == false)
console.log('' == false)
console.log(null == undefined)
console.log(null == false)
console.log(undefined == false)
console.log(NaN == NaN)
console.log(1 == true)
console.log([] == [])
console.log(new Date() == new Date())
console.log({} == {})

/* Logical Operators */
var a = 3
var b = -1
// OR (condition 1 || condition 2)
console.log(true || false)
console.log(false || false)
console.log(false || true)
console.log(a == 3 || b > 0)
console.log(a != 3 || b > 0)
console.log(a != 3 || b < 0)
// AND (condition 1 && condition 2)
console.log(true && false)
console.log(false && false)
console.log(false && true)
console.log(true && true)
console.log(a == 3 && b > 0)
console.log(a != 3 && b > 0)
console.log(a == 3 && b < 0)
// NOT (!condition)
console.log(!false)
console.log(!true)
console.log(!a == 3)
console.log(!a != 3)

/* Special Cases*/
console.log(0 || true)
console.log(0 || 121)
console.log(0 || 'Hunny')
console.log('' || 'Hunny')
console.log('Coders' || undefined)
console.log('Coders' || null)
console.log(false && 'Hunny')
console.log('Cat' && false)
console.log(true && 'Hunny')
console.log('Hunny' && true)
console.log(34 && 312)
console.log(341 && 12)
