var array = new Array('Siam', 'Robiul', 'Dilam', 'Farhad')
// console.log(array)
// console.log(array[0])
// console.log(array[1])
// console.log(array[2])
// console.log(array[3])
// console.log(array[4])
for(i = 0; i < 4; i++) console.log(i, array[i])
console.table(array)